/**
 * Schema and API contract — one tab, two views.
 *
 * They were separate top-level destinations, which split one question
 * ("what does this project's data layer look like?") across two places.
 * Both are generated by the same stage from the same design bundle, so
 * they belong together with a segmented control rather than a route apart.
 */
import { useState } from 'react';

import { ApiContractWorkspace } from '@/features/database/api-contract-page';
import { DatabaseWorkspace } from '@/features/database/database-page';
import { cn } from '@/shared/lib/cn';
import { useWorkspace } from '../workspace-context';
import { BuildRequiredState } from './build-required-state';

type View = 'schema' | 'api';

export function DatabaseTab() {
  const workspace = useWorkspace();
  const [view, setView] = useState<View>('schema');

  if (!workspace.latestRun) return <BuildRequiredState what="the database" />;
  if (!workspace.artifacts) {
    return (
      <BuildRequiredState
        what="the database"
        missing={workspace.artifactsMissing}
        loading={!workspace.artifactsMissing}
      />
    );
  }

  return (
    <div className="space-y-4">
      <div
        role="tablist"
        aria-label="Database views"
        className="inline-flex rounded-md border border-line p-0.5"
      >
        {(
          [
            ['schema', 'Schema'],
            ['api', 'API contract'],
          ] as const
        ).map(([value, label]) => (
          <button
            key={value}
            type="button"
            role="tab"
            aria-selected={view === value}
            onClick={() => {
              setView(value);
            }}
            className={cn(
              'rounded px-3 py-1 text-xs transition-colors',
              'focus-visible:ring-2 focus-visible:ring-accent focus-visible:outline-none',
              view === value ? 'bg-raised font-medium text-fg' : 'text-fg-muted hover:text-fg',
            )}
          >
            {label}
          </button>
        ))}
      </div>

      {view === 'schema' ? <DatabaseWorkspace /> : <ApiContractWorkspace />}
    </div>
  );
}
