/**
 * SQLGenerator: renders the design as MySQL 8 DDL (`schema.sql`).
 *
 * Tables are created first, then indexes, then foreign keys as ALTER
 * statements — so declaration order never breaks referential constraints.
 * Non-negative money/quantity columns get CHECK constraints; enum columns
 * use native MySQL ENUM; audit and soft-delete columns are standardized.
 */
import type {
  ColumnDesign,
  DatabaseDesign,
  OnDelete,
  TableDesign,
} from '../database-designer.types.js';

function columnLine(column: ColumnDesign): string {
  const parts = [`\`${column.name}\``, column.sqlType, column.nullable ? 'NULL' : 'NOT NULL'];

  if (column.defaultExpression === 'uuid()') parts.push('DEFAULT (UUID())');
  else if (column.defaultExpression === 'now()') parts.push('DEFAULT CURRENT_TIMESTAMP');
  else if (column.onUpdateNow) parts.push('DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
  else if (column.enumValues && column.defaultExpression)
    parts.push(`DEFAULT '${column.defaultExpression}'`);

  return parts.join(' ');
}

function createTable(table: TableDesign): string {
  const lines: string[] = [];
  for (const column of table.columns) {
    lines.push(`  ${columnLine(column)}`);
  }
  lines.push(`  PRIMARY KEY (\`${table.primaryKey}\`)`);

  // CHECK constraints for non-negative numeric columns (MySQL 8 enforces these).
  for (const column of table.columns) {
    if (column.nonNegative) {
      lines.push(
        `  CONSTRAINT \`chk_${table.tableName}_${column.name}\` CHECK (\`${column.name}\` >= 0)`,
      );
    }
  }

  return [
    `CREATE TABLE \`${table.tableName}\` (`,
    lines.join(',\n'),
    ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
  ].join('\n');
}

function indexStatements(table: TableDesign): string[] {
  return table.indexes.map((index) => {
    const cols = index.columns.map((c) => `\`${c}\``).join(', ');
    const kind = index.unique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';
    return `${kind} \`${index.name}\` ON \`${table.tableName}\` (${cols});`;
  });
}

const SQL_ON_DELETE: Record<OnDelete, string> = {
  CASCADE: 'CASCADE',
  RESTRICT: 'RESTRICT',
  'SET NULL': 'SET NULL',
  'NO ACTION': 'NO ACTION',
};

function foreignKeyStatements(design: DatabaseDesign): string[] {
  const tableByEntity = new Map(design.tables.map((t) => [t.entity, t.tableName]));
  const statements: string[] = [];

  for (const table of design.tables) {
    for (const column of table.columns) {
      if (!column.references) continue;
      const parentTable = tableByEntity.get(column.references.table);
      if (!parentTable) continue;
      const constraint = `fk_${table.tableName}_${column.name}`;
      statements.push(
        `ALTER TABLE \`${table.tableName}\` ADD CONSTRAINT \`${constraint}\` ` +
          `FOREIGN KEY (\`${column.name}\`) REFERENCES \`${parentTable}\` (\`${column.references.column}\`) ` +
          `ON DELETE ${SQL_ON_DELETE[column.references.onDelete]} ON UPDATE CASCADE;`,
      );
    }
  }
  return statements;
}

export function generateSqlSchema(design: DatabaseDesign): string {
  const out: string[] = [];
  out.push('-- Generated by NexArch Database Designer — MySQL 8 DDL.');
  out.push(`-- Project: ${design.meta.projectName} (${design.meta.projectType})`);
  out.push('-- Normal form: ' + design.meta.normalForm);
  out.push('');
  out.push('SET FOREIGN_KEY_CHECKS = 0;');
  out.push('');

  for (const table of design.tables) {
    out.push(`-- ${table.entity}`);
    out.push(createTable(table));
    out.push('');
  }

  out.push('-- Indexes');
  for (const table of design.tables) {
    for (const statement of indexStatements(table)) out.push(statement);
  }
  out.push('');

  out.push('-- Foreign keys');
  for (const statement of foreignKeyStatements(design)) out.push(statement);
  out.push('');

  out.push('SET FOREIGN_KEY_CHECKS = 1;');
  out.push('');

  return out.join('\n');
}
