/**
 * The complete 10-document package. Distinct from Phase 10's Documentation
 * viewer (README/API/architecture/database/security/deployment-guide/
 * developer-guide) — "modules are islands" means this can't call into
 * workspace's generators even for the four overlapping doc names, so these
 * are independent, generation-time-focused versions plus the four new
 * ones Phase 10 doesn't have: SYSTEM_ARCHITECTURE, CONTRIBUTING,
 * CHANGELOG, LICENSE.
 */
import type { DocumentationBundle, DocumentationFile, QualityArtifacts } from '../quality.types.js';

function readme(artifacts: QualityArtifacts): string {
  const stack = [
    ...(artifacts.requirements?.frontend ?? []),
    ...(artifacts.requirements?.backend ?? []),
  ];
  return `# ${artifacts.projectName}

${artifacts.requirements?.modules?.length ? `A ${artifacts.projectName} application covering: ${artifacts.requirements.modules.join(', ')}.` : `Generated by NexArch.`}

## Tech stack

${stack.length > 0 ? stack.map((s) => `- ${s}`).join('\n') : '- See SYSTEM_ARCHITECTURE.md'}

## Getting started

\`\`\`bash
cp .env.example .env
docker compose up --build
\`\`\`

## Documentation

- [SYSTEM_ARCHITECTURE.md](./SYSTEM_ARCHITECTURE.md) — modules, layers, and design decisions
- [API_DOCUMENTATION.md](./API_DOCUMENTATION.md) — every endpoint
- [DATABASE_DOCUMENTATION.md](./DATABASE_DOCUMENTATION.md) — schema and relationships
- [SECURITY_GUIDE.md](./SECURITY_GUIDE.md) — auth, OWASP compliance, findings
- [DEPLOYMENT_GUIDE.md](./DEPLOYMENT_GUIDE.md) — Docker, CI/CD, environments
- [DEVELOPER_GUIDE.md](./DEVELOPER_GUIDE.md) — conventions and how to extend this project
- [CONTRIBUTING.md](./CONTRIBUTING.md)
- [CHANGELOG.md](./CHANGELOG.md)

## License

See [LICENSE](./LICENSE).
`;
}

function systemArchitecture(artifacts: QualityArtifacts): string {
  const choice = artifacts.architecture?.decisions?.architecture?.choice;
  const backendModuleCount = artifacts.backend?.modules.length ?? 0;
  const frontendPageCount = artifacts.frontend?.pages.length ?? 0;
  const graph = artifacts.dependencyGraph?.stats;

  return `# System Architecture — ${artifacts.projectName}

## Pattern

${choice ?? 'Not yet planned — run the Architecture Planner.'}

## Scale

- ${backendModuleCount} backend module(s)
- ${frontendPageCount} frontend page(s)
${graph ? `- ${graph.totalNodes} dependency graph nodes, ${graph.totalEdges} edges, average depth ${graph.averageDependencyDepth}` : ''}

## Layering

Each backend module owns its own controller → service → repository chain
and never imports another module's internals — cross-module data only
flows through shared types. The frontend mirrors this with a feature-first
folder per page/domain, sharing only UI primitives and the API client
layer.

## Data flow

1. Client calls a versioned REST endpoint (\`/api/v1/...\`).
2. The router validates the request shape, the controller narrows it,
   the service executes business logic, the repository (Prisma) persists it.
3. Responses follow one success envelope and one error envelope across
   every endpoint.

## Where to look

| Concern | Location |
| --- | --- |
| Routes | \`backend/src/modules/*/*.router.ts\` |
| Business logic | \`backend/src/modules/*/*.service.ts\` |
| Validation | \`backend/src/modules/*/*.validator.ts\` |
| Shared types | \`backend/src/shared/types/\` |
| Pages | \`frontend/src/features/*/\` |
| API client | \`frontend/src/shared/services/\` |
`;
}

function apiDocumentation(artifacts: QualityArtifacts): string {
  const routes = artifacts.backend?.routes ?? [];
  const grouped = new Map<string, { method: string; path: string }[]>();
  for (const route of routes) {
    const group = route.path.split('/').find(Boolean) ?? 'root';
    const list = grouped.get(group) ?? [];
    list.push(route);
    grouped.set(group, list);
  }

  const lines = [
    `# API Documentation — ${artifacts.projectName}`,
    '',
    `${routes.length} endpoint(s).`,
    '',
  ];
  for (const [group, groupRoutes] of grouped) {
    lines.push(`## ${group}`, '');
    for (const route of groupRoutes)
      lines.push(`- \`${route.method} /${group === 'root' ? '' : group}...\``);
    lines.push('');
  }
  if (routes.length === 0) lines.push('_No routes available — generate the backend first._');
  return lines.join('\n');
}

function databaseDocumentation(artifacts: QualityArtifacts): string {
  const tables = artifacts.databaseDesign?.tables ?? [];
  const lines = [
    `# Database Documentation — ${artifacts.projectName}`,
    '',
    `Engine: ${artifacts.architecture?.database?.engine ?? 'not yet designed'}`,
    '',
    `${tables.length} table(s): ${tables.map((t) => t.entity).join(', ') || 'none yet'}`,
    '',
    'See `schema.prisma` and `schema.sql` (Database Designer exports) for the full column-level definition.',
  ];
  return lines.join('\n');
}

function securityGuide(artifacts: QualityArtifacts): string {
  const security = artifacts.security;
  const lines = [`# Security Guide — ${artifacts.projectName}`, ''];
  if (security) {
    lines.push(
      `**Score:** ${security.report.overallScore}/100 (${security.report.grade})`,
      '',
      `OWASP Top 10 (2021): ${security.owasp.passed} passed, ${security.owasp.warned} warned, ${security.owasp.failed} failed.`,
      '',
      '## Recommendations',
      '',
      ...security.report.recommendations.map((r) => `- ${r}`),
    );
  } else {
    lines.push('_Run the Security Engine to populate this guide._');
  }
  return lines.join('\n');
}

function deploymentGuide(): string {
  return `# Deployment Guide

See the Deployment Dashboard export for the full, target-specific
deployment guide (Docker, Docker Compose, Vercel, Netlify, Render,
Railway, AWS EC2/ECS, Google Cloud Run, Azure App Service, DigitalOcean,
or local) — that guide is generated per-target and kept alongside the
Docker/CI/CD/environment files it references.
`;
}

function developerGuide(artifacts: QualityArtifacts): string {
  return `# Developer Guide — ${artifacts.projectName}

## Conventions

- Strict TypeScript, no implicit \`any\`.
- Feature-first folders; modules never import each other's internals.
- One success response envelope, one error envelope, applied everywhere.
- Tests live under \`test/\` (backend) and \`test/\` (frontend), generated by
  the Quality Engine — see \`testing-report.json\` for what's already
  scaffolded.

## Adding a feature

1. Plan the change with the Dependency Graph's impact simulation before
   touching code — it tells you exactly which files a change affects.
2. Extend the schema (Prisma) if needed, then the module's
   validator → service → controller → router chain.
3. Add the corresponding frontend feature folder and wire its route.
4. Regenerate tests and documentation from the Quality Engine.

## Modules

${artifacts.backend?.modules.length ? artifacts.backend.modules.map((m) => `- ${m}`).join('\n') : '_No backend modules generated yet._'}
`;
}

function contributing(): string {
  return `# Contributing

## Workflow

1. Fork and branch from \`main\`.
2. Keep commits scoped — one logical change per commit.
3. Run \`npm run lint\` and \`npm test\` before opening a PR.
4. Describe *why* the change is needed, not just what it does.

## Code style

Enforced by ESLint + Prettier — run \`npm run lint:fix\` to auto-fix most
issues before committing.

## Commit messages

Present tense, imperative mood: "add X", "fix Y", not "added X" or
"fixes Y".
`;
}

function changelog(artifacts: QualityArtifacts): string {
  const date = new Date().toISOString().slice(0, 10);
  return `# Changelog

All notable changes to ${artifacts.projectName} are documented here.
Format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).

## [Unreleased]

### Added

- Initial generation via NexArch — requirements analysis, architecture
  plan, database design, backend, frontend, security hardening,
  dependency graph, deployment infrastructure, and this documentation
  package.

## [0.1.0] - ${date}

### Added

- Project scaffolded.
`;
}

function license(): string {
  const year = new Date().getFullYear();
  return `MIT License

Copyright (c) ${year}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;
}

export function generateDocumentationBundle(artifacts: QualityArtifacts): DocumentationBundle {
  const files: DocumentationFile[] = [
    { kind: 'readme', filename: 'README.md', content: readme(artifacts) },
    {
      kind: 'system-architecture',
      filename: 'SYSTEM_ARCHITECTURE.md',
      content: systemArchitecture(artifacts),
    },
    {
      kind: 'api-documentation',
      filename: 'API_DOCUMENTATION.md',
      content: apiDocumentation(artifacts),
    },
    {
      kind: 'database-documentation',
      filename: 'DATABASE_DOCUMENTATION.md',
      content: databaseDocumentation(artifacts),
    },
    { kind: 'security-guide', filename: 'SECURITY_GUIDE.md', content: securityGuide(artifacts) },
    { kind: 'deployment-guide', filename: 'DEPLOYMENT_GUIDE.md', content: deploymentGuide() },
    { kind: 'developer-guide', filename: 'DEVELOPER_GUIDE.md', content: developerGuide(artifacts) },
    { kind: 'contributing', filename: 'CONTRIBUTING.md', content: contributing() },
    { kind: 'changelog', filename: 'CHANGELOG.md', content: changelog(artifacts) },
    { kind: 'license', filename: 'LICENSE', content: license() },
  ];

  return { files };
}
