/**
 * Frontend security: role/permission route guards, a hardened auth store
 * (the access token is memory-only — never persisted to localStorage, so
 * an XSS payload reading storage cannot steal it), and an Axios client that
 * transparently refreshes via the httpOnly refresh-token cookie the
 * Authentication module now issues. Extends Phase 6's output in place —
 * `api-client.ts` and `auth.store.ts` are replaced at the same paths;
 * everything else here is new.
 */
import type { RbacConfig } from '../security-engine.types.js';
import type { GeneratedFile } from '../security-engine.types.js';
import { file } from './file-tree.js';

function permissionMapLiteral(config: RbacConfig): string {
  const byEntity = new Map<string, RbacConfig['permissions']>();
  for (const entry of config.permissions) {
    const list = byEntity.get(entry.entity) ?? [];
    list.push(entry);
    byEntity.set(entry.entity, list);
  }

  const entries = [...byEntity.entries()]
    .map(([entity, entryList]) => {
      const roleLines = entryList
        .map(
          (e) => `    ${JSON.stringify(e.role)}: [${e.actions.map((a) => `'${a}'`).join(', ')}],`,
        )
        .join('\n');
      return `  ${JSON.stringify(entity)}: {\n${roleLines}\n  },`;
    })
    .join('\n');

  return `{\n${entries}\n}`;
}

function permissionsTs(config: RbacConfig): string {
  return `/**
 * Generated by the Security Engine from the same RBAC config the backend
 * enforces — used only to hide UI a user has no access to; the backend's
 * \`requirePermission\` middleware is what actually protects the data.
 */
export type RbacAction = 'create' | 'read' | 'update' | 'delete';

export const PERMISSION_MAP: Record<string, Partial<Record<string, RbacAction[]>>> =
  ${permissionMapLiteral(config)};

export function isPermitted(entity: string, role: string, action: RbacAction): boolean {
  return PERMISSION_MAP[entity]?.[role]?.includes(action) ?? false;
}
`;
}

const roleGuard = `import { Navigate, Outlet, useLocation } from 'react-router-dom';

import { useAuthStore } from '@/shared/store/auth.store';

export interface RoleGuardProps {
  roles: string[];
}

/** Renders the nested route only when the signed-in user holds one of \`roles\`; otherwise sends them to /403. */
export function RoleGuard({ roles }: RoleGuardProps) {
  const userRoles = useAuthStore((state) => state.user?.roles ?? []);
  const location = useLocation();
  const permitted = roles.length === 0 || roles.some((role) => userRoles.includes(role));
  if (!permitted) return <Navigate to="/403" state={{ from: location }} replace />;
  return <Outlet />;
}
`;

const permissionGuard = `import { Navigate, Outlet, useLocation } from 'react-router-dom';

import { useAuthStore } from '@/shared/store/auth.store';
import { isPermitted } from '@/shared/security/permissions';
import type { RbacAction } from '@/shared/security/permissions';

export interface PermissionGuardProps {
  entity: string;
  action: RbacAction;
}

/** Renders the nested route only when the signed-in user's RBAC map grants \`action\` on \`entity\`. */
export function PermissionGuard({ entity, action }: PermissionGuardProps) {
  const userRoles = useAuthStore((state) => state.user?.roles ?? []);
  const location = useLocation();
  const permitted = userRoles.some((role) => isPermitted(entity, role, action));
  if (!permitted) return <Navigate to="/403" state={{ from: location }} replace />;
  return <Outlet />;
}
`;

const forbiddenPage = `import { Link } from 'react-router-dom';

export function ForbiddenPage() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-3 bg-bg px-4 text-center">
      <p className="font-mono text-xs uppercase tracking-widest text-fg-subtle">403</p>
      <h1 className="text-xl font-semibold text-fg">You don't have access to this page</h1>
      <p className="max-w-sm text-sm text-fg-muted">
        Your account role doesn't include the permission this page requires.
      </p>
      <Link to="/" className="mt-2 text-sm font-medium text-accent hover:underline">
        Back to dashboard
      </Link>
    </div>
  );
}
`;

const sessionTimeout = `import { useEffect, useRef } from 'react';

import { useAuthStore } from '@/shared/store/auth.store';

const ACTIVITY_EVENTS = ['mousedown', 'keydown', 'scroll', 'touchstart'] as const;
const DEFAULT_TIMEOUT_MS = 30 * 60 * 1000;

/** Logs the user out after \`timeoutMs\` of no interaction — mitigates a forgotten, unlocked session. */
export function useSessionTimeout(timeoutMs: number = DEFAULT_TIMEOUT_MS): void {
  const logout = useAuthStore((state) => state.logout);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    const reset = (): void => {
      if (timer.current) clearTimeout(timer.current);
      timer.current = setTimeout(() => {
        logout();
        window.location.assign('/login');
      }, timeoutMs);
    };

    reset();
    ACTIVITY_EVENTS.forEach((event) => {
      window.addEventListener(event, reset, { passive: true });
    });

    return () => {
      if (timer.current) clearTimeout(timer.current);
      ACTIVITY_EVENTS.forEach((event) => {
        window.removeEventListener(event, reset);
      });
    };
  }, [logout, timeoutMs]);
}
`;

/* ── src/shared/store/auth.store.ts (replaces Phase 6's) ─────────────────── */

const authStore = `import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface AuthUser {
  id: string;
  email: string;
  name: string;
  roles: string[];
}

interface AuthState {
  accessToken: string | null;
  user: AuthUser | null;
  isAuthenticated: boolean;
  login: (accessToken: string, user: AuthUser) => void;
  setAccessToken: (accessToken: string) => void;
  logout: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      accessToken: null,
      user: null,
      isAuthenticated: false,
      login: (accessToken, user) => {
        set({ accessToken, user, isAuthenticated: true });
      },
      setAccessToken: (accessToken) => {
        set({ accessToken });
      },
      logout: () => {
        set({ accessToken: null, user: null, isAuthenticated: false });
      },
    }),
    {
      name: 'app.auth',
      // The access token is intentionally excluded from persisted storage
      // — it lives in memory only, so an XSS payload reading localStorage
      // cannot exfiltrate it. On reload, the first API call's 401 triggers
      // a silent refresh via the httpOnly refresh-token cookie (see
      // api-client.ts), transparently restoring it.
      partialize: (state) => ({ user: state.user, isAuthenticated: state.isAuthenticated }),
    },
  ),
);
`;

/* ── src/shared/services/api-client.ts (replaces Phase 6's) ──────────────── */

const apiClient = `import axios, { AxiosError } from 'axios';
import type { InternalAxiosRequestConfig } from 'axios';

import { useAuthStore } from '@/shared/store/auth.store';
import type { ApiErrorCode, ApiFailure, ApiSuccess } from '@/shared/types/api';

export class ApiClientError extends Error {
  readonly code: ApiErrorCode;
  readonly status: number | undefined;
  readonly details: ApiFailure['error']['details'];

  constructor(code: ApiErrorCode, message: string, status?: number, details?: ApiFailure['error']['details']) {
    super(message);
    this.name = 'ApiClientError';
    this.code = code;
    this.status = status;
    this.details = details;
  }
}

function isApiFailure(value: unknown): value is ApiFailure {
  return typeof value === 'object' && value !== null && 'success' in value && value.success === false;
}

function readCookie(name: string): string | undefined {
  for (const pair of document.cookie.split('; ')) {
    const [key, value] = pair.split('=');
    if (key === name) return value;
  }
  return undefined;
}

export const apiClient = axios.create({
  baseURL: (import.meta.env.VITE_API_BASE_URL as string | undefined) ?? '/api/v1',
  timeout: 15_000,
  headers: { 'Content-Type': 'application/json' },
  // Required so the browser attaches the httpOnly refresh-token cookie to
  // same-site requests (the CSRF-protected refresh/logout endpoints).
  withCredentials: true,
});

const WRITE_METHODS = new Set(['post', 'put', 'patch', 'delete']);

apiClient.interceptors.request.use((config) => {
  const token = useAuthStore.getState().accessToken;
  if (token) config.headers.Authorization = \`Bearer \${token}\`;
  const csrfToken = readCookie('csrfToken');
  if (csrfToken && config.method && WRITE_METHODS.has(config.method)) {
    config.headers['X-CSRF-Token'] = csrfToken;
  }
  return config;
});

let refreshPromise: Promise<string> | null = null;

/** Single-flight refresh — concurrent 401s share one in-flight request instead of each triggering their own. */
async function refreshAccessToken(): Promise<string> {
  refreshPromise ??= axios
    .post<ApiSuccess<{ accessToken: string }>>(
      \`\${apiClient.defaults.baseURL}/auth/refresh\`,
      {},
      { withCredentials: true },
    )
    .then((response) => {
      const token = response.data.data.accessToken;
      useAuthStore.getState().setAccessToken(token);
      return token;
    })
    .finally(() => {
      refreshPromise = null;
    });
  return refreshPromise;
}

apiClient.interceptors.response.use(
  (response) => response,
  async (error: unknown) => {
    if (error instanceof AxiosError) {
      const original = error.config as (InternalAxiosRequestConfig & { _retried?: boolean }) | undefined;
      const isAuthRoute = original?.url?.includes('/auth/') ?? false;

      if (error.response?.status === 401 && original && !original._retried && !isAuthRoute) {
        original._retried = true;
        try {
          const token = await refreshAccessToken();
          original.headers.Authorization = \`Bearer \${token}\`;
          return apiClient.request(original);
        } catch {
          useAuthStore.getState().logout();
        }
      }

      const body: unknown = error.response?.data;
      if (isApiFailure(body)) {
        throw new ApiClientError(body.error.code, body.message, error.response?.status, body.error.details);
      }
      throw new ApiClientError('NETWORK_ERROR', 'The API is unreachable', error.response?.status);
    }
    throw error instanceof Error ? error : new Error(String(error));
  },
);

export function unwrap<T>(body: ApiSuccess<T>): T {
  return body.data;
}
`;

/* ── src/features/auth/services/auth.service.ts (replaces Phase 6's) ─────── */

const authService = `import { apiClient, unwrap } from '@/shared/services/api-client';
import type { ApiSuccess } from '@/shared/types/api';
import type { AuthUser } from '@/shared/store/auth.store';

export interface LoginPayload {
  email: string;
  password: string;
}

export interface RegisterPayload {
  email: string;
  password: string;
  [key: string]: unknown;
}

export interface AuthResult {
  accessToken: string;
  user: AuthUser;
}

export async function login(payload: LoginPayload): Promise<AuthResult> {
  const response = await apiClient.post<ApiSuccess<AuthResult>>('/auth/login', payload);
  return unwrap(response.data);
}

export async function register(payload: RegisterPayload): Promise<AuthResult> {
  const response = await apiClient.post<ApiSuccess<AuthResult>>('/auth/register', payload);
  return unwrap(response.data);
}

/** Clears the httpOnly refresh-token cookie server-side — call before clearing local auth state. */
export async function logout(): Promise<void> {
  await apiClient.post('/auth/logout');
}
`;

/**
 * Replaces Phase 6's use-auth.ts, which read \`result.token\` — the field
 * the real backend response actually carries is \`accessToken\` (see the
 * Authentication module's controller), so this was a naming mismatch that
 * would only surface once a real backend existed to disagree with it.
 */
const useAuthHooks = `import { useMutation } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';

import { toast } from '@/shared/store/toast.store';
import { useAuthStore } from '@/shared/store/auth.store';
import { login, register } from '../services/auth.service';
import type { LoginPayload, RegisterPayload } from '../services/auth.service';

export function useLogin() {
  const setSession = useAuthStore((state) => state.login);
  const navigate = useNavigate();

  return useMutation({
    mutationFn: (payload: LoginPayload) => login(payload),
    onSuccess: (result) => {
      setSession(result.accessToken, result.user);
      toast('Signed in', 'success');
      void navigate('/');
    },
    onError: (error: Error) => {
      toast(error.message, 'error');
    },
  });
}

export function useRegister() {
  const setSession = useAuthStore((state) => state.login);
  const navigate = useNavigate();

  return useMutation({
    mutationFn: (payload: RegisterPayload) => register(payload),
    onSuccess: (result) => {
      setSession(result.accessToken, result.user);
      toast('Account created', 'success');
      void navigate('/');
    },
    onError: (error: Error) => {
      toast(error.message, 'error');
    },
  });
}
`;

const useAuthLogout = `import { useNavigate } from 'react-router-dom';

import { useAuthStore } from '@/shared/store/auth.store';
import { logout as logoutRequest } from '../services/auth.service';

/** Invalidates the server-side refresh cookie, then clears local auth state and redirects to /login. */
export function useLogout(): () => Promise<void> {
  const clearSession = useAuthStore((state) => state.logout);
  const navigate = useNavigate();

  return async () => {
    try {
      await logoutRequest();
    } finally {
      clearSession();
      void navigate('/login');
    }
  };
}
`;

export function emitFrontendSecurity(config: RbacConfig, authEnabled: boolean): GeneratedFile[] {
  const files: GeneratedFile[] = [
    file('src/shared/security/permissions.ts', 'typescript', permissionsTs(config)),
    file('src/shared/layouts/role-guard.tsx', 'typescriptreact', roleGuard),
    file('src/shared/layouts/permission-guard.tsx', 'typescriptreact', permissionGuard),
    file('src/shared/layouts/forbidden-page.tsx', 'typescriptreact', forbiddenPage),
    file('src/shared/hooks/use-session-timeout.ts', 'typescript', sessionTimeout),
  ];

  if (authEnabled) {
    files.push(
      file('src/shared/store/auth.store.ts', 'typescript', authStore),
      file('src/shared/services/api-client.ts', 'typescript', apiClient),
      file('src/features/auth/services/auth.service.ts', 'typescript', authService),
      file('src/features/auth/hooks/use-auth.ts', 'typescript', useAuthHooks),
      file('src/features/auth/hooks/use-logout.ts', 'typescript', useAuthLogout),
    );
  }

  return files;
}
