/**
 * JWT authentication: signs/verifies short-lived access tokens and
 * longer-lived refresh tokens, and replaces the Phase 5 `auth.ts` scaffold
 * (which accepted any bearer token unconditionally) with real verification.
 * Refresh tokens are stateless (signature + expiry only, no server-side
 * revocation list) — the Database Designer's schema can't be extended with a
 * revocation table from this phase, so this is a documented trade-off (see
 * the security report) rather than a silent gap.
 */
import type { GeneratedFile, JwtConfig } from '../security-engine.types.js';
import { file } from './file-tree.js';

const ISSUER = 'nexarch-generated-api';

export function buildJwtConfig(): JwtConfig {
  return {
    algorithm: 'HS256',
    issuer: ISSUER,
    accessTokenExpiresIn: '15m',
    refreshTokenExpiresIn: '7d',
    refreshTokenStrategy: 'stateless-rotating-cookie',
  };
}

const jwtUtil = `import jwt from 'jsonwebtoken';
import type { SignOptions } from 'jsonwebtoken';

import { config } from '../config/index.js';

const ISSUER = '${ISSUER}';

export interface AccessTokenPayload {
  sub: string;
  roles: string[];
  email?: string;
}

export interface RefreshTokenPayload {
  sub: string;
}

export function signAccessToken(payload: AccessTokenPayload): string {
  return jwt.sign(payload, config.auth.jwtSecret, {
    expiresIn: config.auth.accessTokenExpiresIn as SignOptions['expiresIn'],
    issuer: ISSUER,
  });
}

export function signRefreshToken(payload: RefreshTokenPayload): string {
  return jwt.sign(payload, config.auth.jwtRefreshSecret, {
    expiresIn: config.auth.refreshTokenExpiresIn as SignOptions['expiresIn'],
    issuer: ISSUER,
  });
}

export function verifyAccessToken(token: string): AccessTokenPayload {
  return jwt.verify(token, config.auth.jwtSecret, { issuer: ISSUER }) as unknown as AccessTokenPayload;
}

export function verifyRefreshToken(token: string): RefreshTokenPayload {
  return jwt.verify(token, config.auth.jwtRefreshSecret, {
    issuer: ISSUER,
  }) as unknown as RefreshTokenPayload;
}
`;

const authMiddleware = `import type { RequestHandler } from 'express';

import { ForbiddenError, UnauthorizedError } from '../errors/app-error.js';
import { verifyAccessToken } from '../security/jwt.js';

/**
 * Verifies the bearer token's signature and expiry (generated by the
 * Security Engine) and attaches the real principal — replaces Phase 5's
 * scaffold, which accepted any \`Bearer <token>\` unconditionally.
 */
export const requireAuth: RequestHandler = (req, _res, next) => {
  const header = req.get('Authorization');
  if (!header || !header.startsWith('Bearer ')) {
    next(new UnauthorizedError());
    return;
  }
  try {
    const payload = verifyAccessToken(header.slice(7));
    req.user = { id: payload.sub, roles: payload.roles, email: payload.email };
    next();
  } catch {
    next(new UnauthorizedError('Invalid or expired token'));
  }
};

/** Restrict a route to specific roles — enforced against the verified JWT's roles claim. */
export function requireRoles(...roles: string[]): RequestHandler {
  return (req, _res, next) => {
    if (!req.user) {
      next(new UnauthorizedError());
      return;
    }
    if (roles.length > 0 && !roles.some((role) => req.user?.roles.includes(role))) {
      next(new ForbiddenError());
      return;
    }
    next();
  };
}
`;

const expressTypes = `import 'express';

declare global {
  namespace Express {
    interface UserPrincipal {
      id: string;
      roles: string[];
      email?: string;
    }
    interface Request {
      id: string;
      user?: UserPrincipal;
    }
  }
}

export {};
`;

export function emitJwtAuth(): GeneratedFile[] {
  return [
    file('src/shared/security/jwt.ts', 'typescript', jwtUtil),
    file('src/shared/middleware/auth.ts', 'typescript', authMiddleware),
    file('src/shared/types/express.d.ts', 'typescript', expressTypes),
  ];
}
