/**
 * Password policy: the concrete rule set (length, character classes,
 * history, expiration, bcrypt cost) plus the backend utility that hashes,
 * verifies, and validates passwords against it. `express-shared/security/`
 * is a new namespace — Phase 5 has no password handling at all yet.
 */
import type { GeneratedFile, PasswordPolicy } from '../security-engine.types.js';
import { file } from './file-tree.js';

export function buildPasswordPolicy(): PasswordPolicy {
  return {
    minLength: 10,
    requireUppercase: true,
    requireLowercase: true,
    requireNumber: true,
    requireSymbol: true,
    passwordHistory: 5,
    expirationDays: null,
    bcryptSaltRounds: 12,
  };
}

function passwordUtil(policy: PasswordPolicy): string {
  return `import bcrypt from 'bcryptjs';

import { config } from '../config/index.js';

/**
 * Password policy generated by the Security Engine from the architecture's
 * security plan. \`validatePassword\` returns a human-readable violation per
 * unmet rule — the caller turns that into a 422 (see the Authentication
 * module's register/reset validators).
 */
export const PASSWORD_POLICY = {
  minLength: ${policy.minLength},
  requireUppercase: ${policy.requireUppercase},
  requireLowercase: ${policy.requireLowercase},
  requireNumber: ${policy.requireNumber},
  requireSymbol: ${policy.requireSymbol},
  history: ${policy.passwordHistory},
} as const;

export function validatePassword(password: string): string[] {
  const violations: string[] = [];
  if (password.length < PASSWORD_POLICY.minLength) {
    violations.push(\`Password must be at least \${PASSWORD_POLICY.minLength} characters long.\`);
  }
  if (PASSWORD_POLICY.requireUppercase && !/[A-Z]/.test(password)) {
    violations.push('Password must contain at least one uppercase letter.');
  }
  if (PASSWORD_POLICY.requireLowercase && !/[a-z]/.test(password)) {
    violations.push('Password must contain at least one lowercase letter.');
  }
  if (PASSWORD_POLICY.requireNumber && !/[0-9]/.test(password)) {
    violations.push('Password must contain at least one number.');
  }
  if (PASSWORD_POLICY.requireSymbol && !/[^A-Za-z0-9]/.test(password)) {
    violations.push('Password must contain at least one symbol.');
  }
  return violations;
}

export async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, config.auth.bcryptSaltRounds);
}

export async function verifyPassword(password: string, hash: string): Promise<boolean> {
  return bcrypt.compare(password, hash);
}
`;
}

export function emitPasswordPolicy(policy: PasswordPolicy): GeneratedFile[] {
  return [file('src/shared/security/password.ts', 'typescript', passwordUtil(policy))];
}
