/**
 * Secure defaults + the files that wire them into the generated backend:
 * hardened env validation, cookie/CSRF/rate-limiter utilities, and a
 * replacement `app.ts` that mounts sanitization, cookie parsing, and tiered
 * rate limits alongside Phase 5's existing helmet/cors/compression
 * pipeline. `package.json` and `.env.example` are reproduced byte-for-byte
 * from the Backend Generator's emitter and extended — not guessed — so
 * nothing Phase 5 already declared is silently dropped.
 */
import type { SecurityConfig, GeneratedFile } from '../security-engine.types.js';
import type { SecurityModel } from './security-model.js';
import { file } from './file-tree.js';

export function buildSecurityConfig(model: SecurityModel): SecurityConfig {
  return {
    jwt: {
      algorithm: 'HS256',
      issuer: 'nexarch-generated-api',
      accessTokenExpiresIn: '15m',
      refreshTokenExpiresIn: '7d',
      refreshTokenStrategy: 'stateless-rotating-cookie',
    },
    passwordPolicy: {
      minLength: 10,
      requireUppercase: true,
      requireLowercase: true,
      requireNumber: true,
      requireSymbol: true,
      passwordHistory: 5,
      expirationDays: null,
      bcryptSaltRounds: 12,
    },
    fileSecurity: {
      maxSizeMb: 10,
      allowedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.pdf', '.docx', '.csv'],
      allowedMimeTypes: [
        'image/jpeg',
        'image/png',
        'image/webp',
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'text/csv',
      ],
      virusScanEnabled: false,
    },
    cors: { allowedOrigins: ['http://localhost:5173'], credentials: true },
    rateLimits: { windowMs: 60_000, authMax: 10, apiMax: 100, writeMax: 30 },
    headers: [
      'Strict-Transport-Security',
      'X-Content-Type-Options',
      'X-Frame-Options',
      'Referrer-Policy',
      'Cross-Origin-Resource-Policy',
    ],
    csrfEnabled: model.authEnabled,
    secureCookies: true,
  };
}

/* ── src/shared/config/env.ts (replaces Phase 5's) ──────────────────────── */

const envConfig = `import 'dotenv/config';
import { z } from 'zod';

const schema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().min(1).max(65535).default(4000),
  LOG_LEVEL: z.enum(['error', 'warn', 'info', 'http', 'debug']).default('info'),
  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),
  CORS_ORIGINS: z.string().default('*'),
  // Generated by the Security Engine (Phase 7).
  JWT_SECRET: z.string().min(16).default('change-me-in-production-please'),
  JWT_REFRESH_SECRET: z.string().min(16).default('change-me-refresh-secret-in-production'),
  JWT_ACCESS_EXPIRES_IN: z.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: z.string().default('7d'),
  BCRYPT_SALT_ROUNDS: z.coerce.number().int().min(10).max(15).default(12),
  COOKIE_SECRET: z.string().min(16).default('change-me-cookie-secret-in-production'),
});

const parsed = schema.safeParse(process.env);
if (!parsed.success) {
  const issues = parsed.error.issues.map((i) => '  - ' + i.path.join('.') + ': ' + i.message).join('\\n');
  process.stderr.write('Invalid environment configuration\\n' + issues + '\\n');
  process.exit(1);
}

export const env = parsed.data;
`;

const configIndex = `import { env } from './env.js';

export const config = {
  env: env.NODE_ENV,
  isProduction: env.NODE_ENV === 'production',
  isDevelopment: env.NODE_ENV === 'development',
  server: { port: env.PORT, apiPrefix: '/api/v1', bodyLimit: '1mb' },
  database: { url: env.DATABASE_URL },
  cors: { origins: env.CORS_ORIGINS.split(',').map((o) => o.trim()) },
  auth: {
    jwtSecret: env.JWT_SECRET,
    jwtRefreshSecret: env.JWT_REFRESH_SECRET,
    accessTokenExpiresIn: env.JWT_ACCESS_EXPIRES_IN,
    refreshTokenExpiresIn: env.JWT_REFRESH_EXPIRES_IN,
    bcryptSaltRounds: env.BCRYPT_SALT_ROUNDS,
  },
  cookies: {
    secret: env.COOKIE_SECRET,
    secure: env.NODE_ENV === 'production',
    sameSite: 'strict' as const,
  },
  rateLimits: { windowMs: 60_000, authMax: 10, apiMax: 100, writeMax: 30 },
  logging: { level: env.LOG_LEVEL },
} as const;
`;

/* ── src/shared/security/cookies.ts ──────────────────────────────────────── */

const cookiesUtil = `import type { Request, Response } from 'express';

import { config } from '../config/index.js';

const REFRESH_COOKIE = 'refreshToken';
const REFRESH_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

/** Refresh tokens live in an httpOnly cookie — never reachable from JS, so an XSS payload cannot exfiltrate it. */
export function setRefreshTokenCookie(res: Response, token: string): void {
  res.cookie(REFRESH_COOKIE, token, {
    httpOnly: true,
    secure: config.cookies.secure,
    sameSite: config.cookies.sameSite,
    path: config.server.apiPrefix + '/auth',
    maxAge: REFRESH_MAX_AGE_MS,
  });
}

export function clearRefreshTokenCookie(res: Response): void {
  res.clearCookie(REFRESH_COOKIE, { path: config.server.apiPrefix + '/auth' });
}

export function readRefreshTokenCookie(req: Request): string | undefined {
  const cookies = req.cookies as Record<string, string> | undefined;
  return cookies?.[REFRESH_COOKIE];
}
`;

/* ── src/shared/security/csrf.ts ─────────────────────────────────────────── */

const csrfUtil = `import { randomBytes } from 'node:crypto';

import type { RequestHandler, Response } from 'express';

import { config } from '../config/index.js';
import { ForbiddenError } from '../errors/app-error.js';

const CSRF_COOKIE = 'csrfToken';
const CSRF_HEADER = 'x-csrf-token';

/**
 * Double-submit-cookie CSRF protection for the two cookie-authenticated
 * routes (refresh, logout) — every other route authenticates with a bearer
 * token, which a cross-site request cannot forge, so it doesn't need this.
 */
export const csrfProtection: RequestHandler = (req, _res, next) => {
  const cookies = req.cookies as Record<string, string> | undefined;
  const cookieToken = cookies?.[CSRF_COOKIE];
  const headerToken = req.get(CSRF_HEADER);
  if (!cookieToken || !headerToken || cookieToken !== headerToken) {
    next(new ForbiddenError('CSRF token missing or invalid'));
    return;
  }
  next();
};

/** Issues a fresh CSRF token cookie (readable by the frontend so it can echo it back as a header). */
export function issueCsrfCookie(res: Response): string {
  const token = randomBytes(24).toString('hex');
  res.cookie(CSRF_COOKIE, token, {
    httpOnly: false,
    secure: config.cookies.secure,
    sameSite: config.cookies.sameSite,
    path: '/',
  });
  return token;
}
`;

/* ── src/shared/security/rate-limiters.ts ────────────────────────────────── */

const rateLimiters = `import rateLimit from 'express-rate-limit';

import { config } from '../config/index.js';

const standard = { standardHeaders: 'draft-7', legacyHeaders: false } as const;

/** The default limiter Phase 5 already applied to every route. */
export const apiLimiter = rateLimit({
  windowMs: config.rateLimits.windowMs,
  limit: config.rateLimits.apiMax,
  ...standard,
});

/** Stricter limit on authentication routes — brute-force login/register attempts are the highest-value target. */
export const authLimiter = rateLimit({
  windowMs: config.rateLimits.windowMs,
  limit: config.rateLimits.authMax,
  ...standard,
  message: { success: false, message: 'Too many attempts, please try again later', data: null, meta: {} },
});

/** A slightly tighter limit on writes (create/update/delete) than plain reads. */
export const writeLimiter = rateLimit({
  windowMs: config.rateLimits.windowMs,
  limit: config.rateLimits.writeMax,
  ...standard,
});
`;

/* ── src/app.ts (replaces Phase 5's) ─────────────────────────────────────── */

function appTs(projectName: string): string {
  return `import compression from 'compression';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import type { Express } from 'express';
import helmet from 'helmet';
import swaggerUi from 'swagger-ui-express';

import { config } from './shared/config/index.js';
import { errorHandler, notFoundHandler } from './shared/middleware/error-handler.js';
import { requestContext } from './shared/middleware/request-context.js';
import { requestLogger } from './shared/middleware/request-logger.js';
import { sanitizeInput } from './shared/middleware/sanitize.js';
import { apiLimiter } from './shared/security/rate-limiters.js';
import { buildApiRouter } from './routes.js';
import { openApiDocument } from './docs/openapi.js';

/**
 * ${projectName} API — assembled here, listened on in index.ts.
 * Pipeline order: context → security headers → CORS → cookies → parsing →
 * sanitization → logging → rate limit → docs → modules → 404 → errors.
 *
 * Content-Security-Policy is intentionally left off the global helmet
 * config: this process only ever serves JSON plus the Swagger UI docs page
 * (which needs inline styles/scripts CSP would block) — CSP belongs on the
 * surface that actually renders untrusted HTML, i.e. the generated
 * frontend's hosting layer, not a JSON API.
 */
export function createApp(): Express {
  const app = express();
  app.disable('x-powered-by');
  app.set('trust proxy', 1);

  app.use(requestContext);
  app.use(
    helmet({
      contentSecurityPolicy: false,
      hsts: { maxAge: 15_552_000, includeSubDomains: true, preload: true },
      referrerPolicy: { policy: 'no-referrer' },
      crossOriginResourcePolicy: { policy: 'same-site' },
    }),
  );
  app.use(
    cors({
      origin: config.cors.origins.includes('*') ? true : config.cors.origins,
      credentials: true,
    }),
  );
  app.use(compression());
  app.use(cookieParser(config.cookies.secret));
  app.use(express.json({ limit: config.server.bodyLimit }));
  app.use(express.urlencoded({ extended: false, limit: config.server.bodyLimit }));
  app.use(sanitizeInput);
  app.use(requestLogger);
  app.use(apiLimiter);

  app.get(config.server.apiPrefix + '/health', (_req, res) => {
    res.json({ success: true, message: 'OK', data: { status: 'ok' }, meta: {} });
  });

  app.use('/docs', swaggerUi.serve, swaggerUi.setup(openApiDocument));
  app.use(config.server.apiPrefix, buildApiRouter());

  app.use(notFoundHandler);
  app.use(errorHandler);

  return app;
}
`;
}

/* ── package.json (replaces Phase 5's, additively) ───────────────────────── */

function packageJson(model: SecurityModel): GeneratedFile {
  const pkg = {
    name:
      model.projectName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '') || 'generated-backend',
    version: '0.1.0',
    private: true,
    type: 'module',
    description: `Generated backend for ${model.projectName} (${model.projectType}) — produced by the NexArch Backend Generation Engine, hardened by the Security Engine.`,
    scripts: {
      dev: 'tsx watch --clear-screen=false src/index.ts',
      build: 'tsc -p tsconfig.json',
      start: 'node dist/index.js',
      typecheck: 'tsc --noEmit',
      lint: 'eslint src',
      test: 'jest',
      'db:generate': 'prisma generate',
      'db:migrate': 'prisma migrate dev',
      'db:deploy': 'prisma migrate deploy',
    },
    dependencies: {
      '@prisma/client': '^6.8.0',
      bcryptjs: '^2.4.3',
      compression: '^1.8.0',
      'cookie-parser': '^1.4.7',
      cors: '^2.8.5',
      dotenv: '^16.5.0',
      express: '^5.1.0',
      'express-rate-limit': '^7.5.0',
      helmet: '^8.1.0',
      jsonwebtoken: '^9.0.2',
      multer: '^2.0.1',
      'swagger-ui-express': '^5.0.1',
      winston: '^3.17.0',
      zod: '^3.25.0',
      morgan: '^1.10.0',
    },
    devDependencies: {
      '@eslint/js': '^9.25.0',
      '@types/bcryptjs': '^2.4.6',
      '@types/compression': '^1.7.5',
      '@types/cookie-parser': '^1.4.7',
      '@types/cors': '^2.8.17',
      '@types/express': '^5.0.1',
      '@types/jest': '^29.5.14',
      '@types/jsonwebtoken': '^9.0.7',
      '@types/morgan': '^1.9.9',
      '@types/multer': '^1.4.12',
      '@types/node': '^22.15.0',
      '@types/supertest': '^6.0.2',
      '@types/swagger-ui-express': '^4.1.7',
      eslint: '^9.25.0',
      jest: '^29.7.0',
      prisma: '^6.8.0',
      supertest: '^7.1.0',
      'ts-jest': '^29.2.5',
      tsx: '^4.19.0',
      typescript: '^5.8.0',
      'typescript-eslint': '^8.31.0',
    },
  };
  return file('package.json', 'json', JSON.stringify(pkg, null, 2));
}

function envExample(): GeneratedFile {
  return file(
    '.env.example',
    'env',
    `NODE_ENV=development
PORT=4000
LOG_LEVEL=debug
DATABASE_URL="mysql://user:password@localhost:3306/database"
CORS_ORIGINS=http://localhost:5173
# Generated by the Security Engine (Phase 7).
JWT_SECRET=change-me-in-production-please
JWT_REFRESH_SECRET=change-me-refresh-secret-in-production
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d
BCRYPT_SALT_ROUNDS=12
COOKIE_SECRET=change-me-cookie-secret-in-production
`,
  );
}

export function emitSecurityConfig(model: SecurityModel): GeneratedFile[] {
  return [
    file('src/shared/config/env.ts', 'typescript', envConfig),
    file('src/shared/config/index.ts', 'typescript', configIndex),
    file('src/shared/security/cookies.ts', 'typescript', cookiesUtil),
    file('src/shared/security/csrf.ts', 'typescript', csrfUtil),
    file('src/shared/security/rate-limiters.ts', 'typescript', rateLimiters),
    file('src/app.ts', 'typescript', appTs(model.projectName)),
    packageJson(model),
    envExample(),
  ];
}
