-- AlterTable
ALTER TABLE `graph_edges` MODIFY `relationship` ENUM('CONTAINS', 'IMPLEMENTS', 'DEPENDS_ON', 'USES', 'CALLS', 'EXPOSES', 'PERSISTS', 'BELONGS_TO', 'GENERATES', 'VALIDATES', 'TESTS', 'SECURED_BY', 'TARGETS') NOT NULL;
-- AlterTable
ALTER TABLE `graph_nodes` MODIFY `type` ENUM('PROJECT', 'REQUIREMENT', 'FEATURE', 'COMPONENT', 'SERVICE', 'API', 'ENTITY', 'FIELD', 'FILE', 'MODULE', 'SECURITY_RULE', 'DEPENDENCY', 'TEST', 'FINDING') NOT NULL;
